---
- name: enable yum repository
  yum_repository:
    name: grafana
    description: grafana upstream yum repo
    baseurl: "{{ grafana.grafana_repo }}"
    gpgcheck: yes
    gpgkey: "{{ grafana.grafana_repo_key }}"

- name: import rpm key
  rpm_key:
    key: "{{ grafana.grafana_repo_key }}"
    state: present
