---
- name: install java
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - java-1.8.0-openjdk

- name: create working directories
  file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
    owner: root
  with_items:
    - "/opt/app/bin"

- name: render service startup script
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    mode: "0755"
  with_items:
    - { src: 'templates/start.sh.j2', dest: '/opt/app/bin/{{ app.service }}-start.sh' }
    - { src: 'templates/service.j2',  dest: '/etc/systemd/system/{{ app.service }}.service' }
  notify: restart service
